import { GoogleGenAI, Type, ThinkingLevel, GenerateContentResponse } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const withRetry = async <T>(fn: () => Promise<T>, retries = 3, delay = 1000): Promise<T> => {
  try {
    return await fn();
  } catch (error: any) {
    if (retries > 0 && (error.status === 429 || error.message?.includes('429') || error.message?.includes('RESOURCE_EXHAUSTED'))) {
      console.warn(`Gemini API rate limited. Retrying in ${delay}ms... (${retries} retries left)`);
      await sleep(delay);
      return withRetry(fn, retries - 1, delay * 2);
    }
    throw error;
  }
};

const getAIClient = (userKey?: string) => {
  if (userKey) return new GoogleGenAI({ apiKey: userKey });
  return ai;
};

export const generateProject = async (prompt: string, currentFiles: { name: string, code: string }[] = [], useThinking: boolean = false, userKey?: string) => {
  const client = getAIClient(userKey);
  const config: any = {
    temperature: 0.7,
    responseMimeType: "application/json",
    responseSchema: {
      type: Type.OBJECT,
      properties: {
        files: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: "The filename including path (e.g. src/App.js)" },
              code: { type: Type.STRING, description: "The content of the file" },
              language: { type: Type.STRING, description: "The language of the file" }
            },
            required: ["name", "code", "language"]
          }
        }
      },
      required: ["files"]
    }
  };

  const model = useThinking ? "gemini-3.1-pro-preview" : "gemini-3-flash-preview";

  if (useThinking) {
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.HIGH };
  } else {
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.LOW };
  }

  const context = currentFiles.length > 0 
    ? `Current Project Files:\n${currentFiles.map(f => `FILE: ${f.name}\n${f.code}\n---`).join('\n')}`
    : "No existing files.";

  const response = await withRetry(() => client.models.generateContent({
    model,
    contents: `Act as a senior software engineer. Generate a full project structure for the following request. 
    You MUST provide a complete, working application with multiple files organized in a logical directory structure (e.g., src/components/, src/utils/, etc.).
    
    ${context}
    
    Request: ${prompt}
    
    Return a JSON object with a "files" array. Each file object MUST have:
    - "name": The full path and filename (e.g., "src/components/Header.js").
    - "code": The complete source code for that file.
    - "language": The programming language (e.g., "javascript", "css", "html").`,
    config,
  }));
  
  try {
    return JSON.parse(response.text);
  } catch (e) {
    console.error("Failed to parse AI project response:", response.text);
    throw new Error("Invalid project structure generated by AI");
  }
};

export const generateCode = async (prompt: string, language: string = "javascript", useThinking: boolean = false, userKey?: string) => {
  const client = getAIClient(userKey);
  const config: any = {
    temperature: 0.7,
  };

  // Use Flash for speed, Pro only for thinking
  const model = useThinking ? "gemini-3.1-pro-preview" : "gemini-3-flash-preview";

  if (useThinking) {
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.HIGH };
  } else {
    // Minimize latency for non-thinking tasks
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.LOW };
  }

  const response = await withRetry(() => client.models.generateContent({
    model,
    contents: `Act as a senior software engineer. Generate high-quality, professional code for the following request in ${language}. 
    If the request is for a web app, provide HTML, CSS, and JS combined into a single HTML structure if possible, or separate blocks.
    Request: ${prompt}`,
    config,
  }));
  return response.text;
};

export const generateCodeStream = async (prompt: string, language: string = "javascript", useThinking: boolean = false, onChunk: (text: string) => void, userKey?: string) => {
  const client = getAIClient(userKey);
  const config: any = {
    temperature: 0.7,
  };

  const model = useThinking ? "gemini-3.1-pro-preview" : "gemini-3-flash-preview";

  if (useThinking) {
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.HIGH };
  } else {
    config.thinkingConfig = { thinkingLevel: ThinkingLevel.LOW };
  }

  const response = await client.models.generateContentStream({
    model,
    contents: `Act as a senior software engineer. Generate high-quality, professional code for the following request in ${language}. 
    If the request is for a web app, provide HTML, CSS, and JS combined into a single HTML structure if possible, or separate blocks.
    Request: ${prompt}`,
    config,
  });

  let fullText = "";
  for await (const chunk of response) {
    const text = chunk.text;
    if (text) {
      fullText += text;
      onChunk(fullText);
    }
  }
  return fullText;
};

export const fastFix = async (code: string, language: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3.1-flash-lite-preview",
    contents: `Quickly identify and fix the most obvious bug in this ${language} code. Return ONLY the fixed code.
    Code:
    ${code}`,
    config: {
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    }
  }));
  return response.text;
};

export const debugCode = async (code: string, language: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3-flash-preview", // Switched to flash for speed
    contents: `Debug the following ${language} code. Identify errors, explain them, and provide the fixed code.
    Code:
    ${code}`,
    config: {
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    }
  }));
  return response.text;
};

export const processVoiceCommand = async (transcript: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3-flash-preview", // Switched to flash for speed
    contents: `The user said: "${transcript}". 
    Interpret this as a coding or IDE command. 
    Possible intents:
    - "build": Generate new code or a new feature.
    - "fix": Fix a bug in the current code.
    - "open": Open a specific file.
    - "save": Save the current file.
    - "run": Run the code or debugger.
    - "search": Search for something in the project.
    - "create": Create a new file.
    - "delete": Delete a file.
    - "theme": Change the theme (e.g., "switch to midnight").
    - "clear": Clear the terminal or console.
    - "explain": Explain the current code or file.
    - "review": Trigger a project review or security audit.
    - "test": Run unit tests.
    - "dictate": Dictate code to be inserted at the cursor.
    - "format": Format the current file.
    - "other": Anything else.

    Return a JSON object with:
    {
      "intent": "build" | "fix" | "open" | "save" | "run" | "search" | "create" | "delete" | "theme" | "clear" | "explain" | "review" | "test" | "dictate" | "format" | "other",
      "description": "clear description of the task or parameter (e.g., filename for 'open', query for 'search', theme name for 'theme')",
      "suggestedLanguage": "javascript" | "python" | "html" | etc
    }`,
    config: {
      responseMimeType: "application/json",
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          intent: { type: Type.STRING },
          description: { type: Type.STRING },
          suggestedLanguage: { type: Type.STRING }
        },
        required: ["intent", "description", "suggestedLanguage"]
      }
    }
  }));
  return JSON.parse(response.text);
};

export const getGhostText = async (codeBefore: string, codeAfter: string, language: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3.1-flash-lite-preview",
    contents: `Act as an AI pair programmer. Provide a short, relevant code completion for the following context.
    Language: ${language}
    Code before cursor:
    ${codeBefore}
    Code after cursor:
    ${codeAfter}
    
    Return ONLY the suggested code completion, no explanations or markdown blocks. Keep it concise.`,
    config: {
      temperature: 0.2,
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    }
  }));
  return response.text;
};

export const manipulateCode = async (code: string, language: string, action: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3-flash-preview", // Switched to flash for speed
    contents: `Act as a senior software engineer. Perform the following action on the provided ${language} code snippet.
    Action: ${action}
    Code:
    ${code}
    
    Return ONLY the modified code snippet, no explanations or markdown code blocks.`,
    config: {
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    }
  }));
  return response.text;
};

export const getSmartSuggestions = async (code: string, language: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Act as a senior software engineer. Analyze the following ${language} code and provide 3-5 specific, actionable suggestions for improvement. 
    Focus on:
    - Performance
    - Readability
    - Security
    - Best practices
    - Potential bugs
    
    Code:
    ${code}
    
    Return a JSON array of objects:
    [
      {
        "title": "Short title of the suggestion",
        "description": "Detailed explanation of why this is better",
        "type": "performance" | "readability" | "security" | "bug" | "best-practice",
        "impact": "high" | "medium" | "low",
        "suggestedCode": "The specific code snippet to apply (optional)"
      }
    ]`,
    config: {
      responseMimeType: "application/json",
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            description: { type: Type.STRING },
            type: { type: Type.STRING },
            impact: { type: Type.STRING },
            suggestedCode: { type: Type.STRING }
          },
          required: ["title", "description", "type", "impact"]
        }
      }
    }
  }));
  return JSON.parse(response.text);
};

export const detectDependencies = async (code: string, language: string, userKey?: string) => {
  const client = getAIClient(userKey);
  const response = await withRetry(() => client.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze the following ${language} code and identify all third-party npm packages that are imported or required but not part of the standard library.
    
    Code:
    ${code}
    
    Return a JSON array of strings, each being a package name (e.g., ["lodash", "axios", "express"]). If no packages are found, return an empty array [].`,
    config: {
      responseMimeType: "application/json",
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
      responseSchema: {
        type: Type.ARRAY,
        items: { type: Type.STRING }
      }
    }
  }));
  return JSON.parse(response.text);
};

export const chatWithAI = async (message: string, history: { role: string, parts: { text: string }[] }[], userKey?: string) => {
  const client = getAIClient(userKey);
  const chat = client.chats.create({
    model: "gemini-3-flash-preview", // Switched to flash for speed
    config: {
      systemInstruction: "You are Nexus AI, a professional coding assistant. You help developers build, debug, and optimize their code. Be concise, technical, and helpful.",
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    },
    history,
  });

  const response = await chat.sendMessage({ message });
  return response.text;
};

export const chatWithAIStream = async (message: string, history: { role: string, parts: { text: string }[] }[], onChunk: (text: string) => void, userKey?: string) => {
  const client = getAIClient(userKey);
  const chat = client.chats.create({
    model: "gemini-3-flash-preview",
    config: {
      systemInstruction: "You are Nexus AI, a professional coding assistant. You help developers build, debug, and optimize their code. Be concise, technical, and helpful.",
      thinkingConfig: { thinkingLevel: ThinkingLevel.LOW }
    },
    history,
  });

  const response = await chat.sendMessageStream({ message });
  let fullText = "";
  for await (const chunk of response) {
    const text = (chunk as GenerateContentResponse).text;
    if (text) {
      fullText += text;
      onChunk(fullText);
    }
  }
  return fullText;
};
